---
offlineSearch: true

ui:
  sidebar_menu_compact: true
  sidebar_menu_foldable: true

links:
  developer:
    - name: "GitHub"
      url: "https://github.com/orgs/camptocamp"
      icon: "fab fa-github"
